project:
  type: website
  output-dir: docs

adsense:
    client: "ca-pub-9616514614388484"
    slot: "5226569652"

website:
  cookie-consent:
    type: express
    palette: dark
  favicon: Stravawattz.tif

format:
  html:
    theme:
      - darkly
      - styles.scss
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9616514614388484"
            crossorigin="anonymous"></script>
    include-before-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9616514614388484"
            crossorigin="anonymous"></script>
          <!-- stravawattz_vertical -->
          <ins class="adsbygoogle"
            style="display:block"
            data-ad-client="ca-pub-9616514614388484"
            data-ad-slot="5226569652"
            data-ad-format="auto"
            data-full-width-responsive="true"></ins>
          <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
          </script>

