# website settings
website:

  # Parameters
  favicon: /documenten/favicon.png
  twitter-card: true
  #site-url: https://example.com
  
  # # Nieuwsbericht
  # announcement:
  #    icon: info-square-fill
  #    dismissable: true
  #    content: "**Nieuw artikel !** [Bekijk hier uw advocaat in het nieuws](/nieuws/hln-20220224.qmd)"
  #    type: light
  #    position: above-navbar
  
  # Navigation bar
  navbar:
    pinned: false
    collapse: true
    collapse-below: "md"
    menu: 
    
    # Pagina's
    left:
      - text: "<b style='color: #FF331F;'><u>Advocaat Julie Goyvaerts</u></b>"
        href: index.qmd
      - text: "Expertise"
        href: expertise.qmd
      - text: "Tarieven"
        href: tarieven.qmd
      - text: "Vervangingen"
        href: vervanging.qmd
      - text: "Nieuws"
        href: nieuws.qmd
      - text: "Contact"
        href: contact.qmd
    
    # Contact knoppen
    right:
      - icon: telephone
        href: "tel:0032493861566"
      - icon: whatsapp
        href: "https://wa.link/v9j1jp"
        target: "_blank"
      - icon: envelope
        href: "mailto:julie.goyvaerts@advocaat.be"  
      - icon: linkedin
        href: "https://www.linkedin.com/in/juliegoyvaerts/"
        
  # Zoekbalk
  search: 
    location: navbar
    type: textbox

  # Onderkant van pagina
  page-footer:
    center: <span>&#169; 2025 Advocaat Julie Goyvaerts | <a href="/documenten/Algemene-Voorwaarden-Advocaat-Julie-Goyvaerts.pdf" target="_blank">Algemene voorwaarden</a> | <a href="/documenten/Privacybeleid-Advocaat-Julie-Goyvaerts.pdf" target="_blank">Privacybeleid</a></span>

project:
  type: website
  output-dir: docs

  # preview: 
  #   port: 22222
  #   browser: true
  #   watch-inputs: true
  #   navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme:
      - lumen
      - styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    
language: 
  search-text-placeholder:
    Zoeken