---
title: <br>Tarieven en erelonen
---

<br>

**Mijn tarieven helder uitgelegd**

Afhankelijk van uw situatie kunnen we bekijken welke financiele afspraak het beste past bij uw juridisch probleem (bv. een vast uurtarief, rechtsbijstandverzekering of een gratis advocaat). Een eerste kennismaking (incl. advies) is gratis en vrijblijvend. Hieronder vindt u de mogelijkheden.

<br>

------------------------------------------------------------------------

<br>

**Optie 1: Het uurtarief** – *€150,00 (excl. btw)*

Voor de meeste inhoudelijke diensten stel ik een uurtarief voor. Dit ereloon kan echter variëren naargelang de complexiteit en hoogdringendheid van de zaak. Ik vind het belangrijk om hierover helder en transparant te communiceren. Daarom brengen ik u regelmatig op de hoogte van de voortgang en ontvangt u een overzicht van onze werkzaamheden.

Dit uurtarief wordt vermeerderd met eventuele gemaakte kosten, waarbij volgende standaardtarieven (excl. BTW) worden gehanteerd:

- Opening dossier: 50 euro
- Brief - dactylo: 11 euro
- Inkomende schrijvens: € 0,50
- Uitgaande schrijvens: €11/ brief
- Werkingskost kantoor (telefonie): forfait €25/maand
- Verplaatsingskost: € 0,50 /km
- Verplaatsingstijd: €60/ u
- Aangetekende brief: het geldend tarief voor aantekentaks
- Kopie: 0,50 euro

<br>

------------------------------------------------------------------------

<br>

**Optie 2: Rechtsbijstand** – *Autoverzekering, brandverzekering, familiale verzekering, ...*

Heeft u te maken met een verkeersovertreding, een (schade)ongeval of strafrechtelijke procedure? Vaak is rechtsbijstand inbegrepen in uw autoverzekering en dekt deze alle kosten van de juridische bijstand. U hebt vrije keuze van advocaat en kan zelf een advocaat voorstellen aan uw verzekeraar. Ook de familiale verzekering, de brandverzekering of een aparte polis rechtsbijstand komt soms tussen in de kosten van bepaalde juridische procedures. Aarzel niet om navraag te doen bij uw verzekeraar.


<br>

------------------------------------------------------------------------

<br>

**Optie 3: Gratis advocaat** – *Pro Deo*

Iedereen heeft recht op juridische bijstand, maar voor mensen met een laag inkomen kan het moeilijk zijn om deze kosten te dragen. In dit geval kan u beroep doen op een pro-Deo advocaat die (afhankelijk van uw inkomen) gratis of tegen een sterk gereduceerd tarief werkt.

Als Pro Deo advocaat biedt ik u net als bij andere cliënten juridisch advies, ondersteuning en vertegenwoordiging. De kosten worden door de Belgische Staat gedragen, zodat u zich geen zorgen hoeft te maken over de betaling.

Wat de maximumgrens van je inkomen mag zijn, is afhankelijk van je gezinssituatie. Dit bepaalt of je een volledig gratis, of gedeeltelijk gratis advocaat kan krijgen. De voorwaarden worden op <a href="https://www.advocaat.be/nl/fetch-asset?path=ovb/Documenten/toegang-tot-het-recht/2024_20240901_inkomensgrenzen_juridische_tweedelijnsbijstand.pdf" target="_blank">deze website</a> beschreven. Ik bekijk graag samen met u of u in aanmerking komt voor een gratis advocaat.

<br>

------------------------------------------------------------------------

<br>


**Contactgegevens:**

Advocaat Julie Goyvaerts<br> Kasteelpleinstraat 79<br>2000 Antwerpen<br>

Telefoon: <a href="tel:0032493861566">+32 493 86 15 66</a><br>E-mail: <a href="mailto:julie.goyvaerts@advocaat.be">julie.goyvaerts@advocaat.be</a><br>

KBO-nummer: BE0751.922.224<br>Derdenrekening: BE85 6304 2321 5406<br><br>

```{=html}
<div style = "margin: 0px; text-align: left;">
<a class="btn btn-primary" href="/contact.qmd" role="button" style="padding: 5px 5px; text-transform: none;">Neem contact op</a>
</div>
```

